# Generated by Django 3.0.2 on 2020-01-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='silver_with_bill_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=21, null=True),
        ),
    ]
