# Generated by Django 3.0.1 on 2020-01-01 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('F', 'FeMale'), ('M', 'Male')], max_length=1)),
                ('job', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_one', models.CharField(max_length=10)),
                ('mobile_two', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_one', models.CharField(blank=True, max_length=100, null=True)),
                ('address_two', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(choices=[('IND', 'India'), ('USA', 'United States of America'), ('CAN', 'Canada'), ('CHN', 'China'), ('ARE', 'United Arab Emirates')], default='IND', max_length=3)),
                ('detail', models.TextField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
