# Generated by Django 3.0.2 on 2020-01-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='created',
            new_name='date_added',
        ),
    ]
