# Generated by Django 3.0.1 on 2020-01-01 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_one',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Only 10 Digit Mobile Number Allowed', regex="@'^[0-9]{10}$'")]),
        ),
    ]
