# Generated by Django 3.0.1 on 2020-01-01 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200101_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_one',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Only 10 Digit Mobile Number Allowed', regex='^[1-9]\\d{9}$')]),
        ),
    ]
