# Generated by Django 3.0.1 on 2020-01-01 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200101_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only Alphabets Allowed', regex='/^[a-zA-Z ]*$/')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_two',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Only 10 Digit Mobile Number Allowed', regex='^[1-9]\\d{9}$')]),
        ),
    ]
