# Generated by Django 3.0.1 on 2020-01-01 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200101_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only Alphabets Allowed', regex='^[a-zA-Z]*$')]),
        ),
    ]
