# Generated by Django 3.0.1 on 2020-01-01 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200101_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='ફક્ત આંકડા જ સાચી ભરણી છે', regex='^[a-zA-Z]*$')]),
        ),
    ]
