# Generated by Django 3.0.1 on 2020-01-01 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20200101_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='detail',
            field=models.TextField(blank=True, help_text='Maximum 300 Characters Allowed', max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=300)]),
        ),
    ]
